version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - backend  
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: postgresql://caryn@postgres/trivia
  postgres:
    build:
      dockerfile: Dockerfile
      context: ./postgres
    environment:
      POSTGRES_USER: caryn
      POSTGRES_DB: trivia
      POSTGRES_HOST_AUTH_METHOD: trust